# global settings
exclude: ["node_modules"]

# Site settings
title: Caecs Dia
username: eviao
email: eviao.dev@gmail.com
description: "."
baseurl: ""
url: "http://eviao.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
