# global settings
exclude: ["node_modules"]

# Site settings
title: "Caecs Dia"
description: ""
baseurl: ""
url: "http://eviao.github.io"

# Owner settings
owner:
  name:         "eviao"
  avatar:       
  bio:          "i'm programmer."
  email:        "eviao.dev@gmail.com"      
  github:       "eviao" 

# Build settings
markdown: kramdown
permalink: /:categories/:title
