# global settings
exclude: ["node_modules"]

# Site settings
title: Caecs Dia
username: eviao
email: eviao.dev@gmail.com
description: "."
baseurl: ""
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown
permalink: /:categories/:title
